/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipos;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;


/**
 *
 * @author Hugo
 */
public class vitoria_panel extends javax.swing.JPanel {

    /**
     * Creates new form vitoria_panel
     */
    Jogo j;
    
    public vitoria_panel(Jogo j) {
        this.j=j;
        initComponents();
        inicializa();
    }
    
    public Cursor setCursor(int i){
        Image image;
        Toolkit tk = Toolkit.getDefaultToolkit();
        if(i==1)
            image = tk.getImage(getClass().getResource("/imagens/atras.png"));
        else
            image = tk.getImage(getClass().getResource("/imagens/seta2.png"));
        
        Cursor cursor = tk.createCustomCursor(image, getLocation(), "meuCursor");
        
        
        return cursor;
    }
    
    public void inicializa()
    {
        lbl_nome.setText(j.getJogador(j.getIdVencedor()).getNome());
        if(j.getTipoJog()==2)
        {
            j.getJogador(j.getIdVencedor()).setGanhos(j.getJogador(j.getIdVencedor()).getGanhos()+1);//actualiza jogos ganhos
            j.getAcessoBd().gravarVencedor(j.getJogador(j.getIdVencedor()).getGanhos(), j.getJogador(j.getIdVencedor()).getNome());
        }
        
        //muda o jogador activo para o que perdeu começar a jogar a seguir
        if(j.getIdVencedor()==0)
            j.setEstados(new Estado_DoisJogadores(j));
        else
            j.setEstados(new Estado_UmJogador(j));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_ret = new javax.swing.JButton();
        bt_jogar_novamente = new javax.swing.JButton();
        lbl_nome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        bt_ret.setBorder(null);
        bt_ret.setBorderPainted(false);
        bt_ret.setContentAreaFilled(false);
        bt_ret.setCursor(setCursor(1));
        bt_ret.setFocusPainted(false);
        bt_ret.setFocusable(false);
        bt_ret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_retActionPerformed(evt);
            }
        });
        add(bt_ret);
        bt_ret.setBounds(100, 523, 60, 60);

        bt_jogar_novamente.setFont(new java.awt.Font("Alice in Wonderland", 0, 32)); // NOI18N
        bt_jogar_novamente.setForeground(new java.awt.Color(255, 255, 255));
        bt_jogar_novamente.setText("Jogar Novamente");
        bt_jogar_novamente.setBorder(null);
        bt_jogar_novamente.setBorderPainted(false);
        bt_jogar_novamente.setContentAreaFilled(false);
        bt_jogar_novamente.setCursor(setCursor(2));
        bt_jogar_novamente.setFocusPainted(false);
        bt_jogar_novamente.setFocusable(false);
        bt_jogar_novamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_jogar_novamenteActionPerformed(evt);
            }
        });
        add(bt_jogar_novamente);
        bt_jogar_novamente.setBounds(330, 480, 290, 100);

        lbl_nome.setFont(new java.awt.Font("Alice in Wonderland", 0, 48)); // NOI18N
        lbl_nome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nome.setText("Hugo Duarte");
        add(lbl_nome);
        lbl_nome.setBounds(360, 190, 230, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ganhar.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 1000, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_jogar_novamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_jogar_novamenteActionPerformed
        j.getEcra().getVit_panel().setVisible(false);
        j.getEcra().getJogo_panel().setVisible(true);
        j.setIdVencedor(-1);//reseta o vencedor
        j.zeraPintaBotoes();//inicializa matriz que recebe os botoes vencedores
    }//GEN-LAST:event_bt_jogar_novamenteActionPerformed

    private void bt_retActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_retActionPerformed
        j.getEcra().getVit_panel().setVisible(false);
        j.setEstados(new Estado_Perfil(j,j.getTipoJog()));
        j.setGuardaFimJogo(-1);//coloca o fim do jogo a -1
        j.deleteObservers();//apaga observers
        j.setIdVencedor(-1);//reseta o vencedor
        
        if(j.getTipoJog()==1)
            j.addObserver(j.getEcra().getPrincipal1_panel());//adiciona o observer a janela
        else
            j.addObserver(j.getEcra().getPrincipal2_panel());//adiciona o observer a janela
    }//GEN-LAST:event_bt_retActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_jogar_novamente;
    private javax.swing.JButton bt_ret;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_nome;
    // End of variables declaration//GEN-END:variables
}
