/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipos;

/**
 *
 * @author Hugo
 */
public class Registo_panel extends javax.swing.JPanel {

    /**
     * Creates new form Registo_panel
     */
    public Registo_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_ok = new javax.swing.JButton();
        tb_utilizador = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt_ret = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 650));
        setRequestFocusEnabled(false);
        setLayout(null);

        bt_ok.setFont(new java.awt.Font("Alice in Wonderland", 0, 36)); // NOI18N
        bt_ok.setText("OK");
        bt_ok.setContentAreaFilled(false);
        bt_ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(bt_ok);
        bt_ok.setBounds(440, 500, 110, 80);

        tb_utilizador.setFont(new java.awt.Font("Alice in Wonderland", 0, 36)); // NOI18N
        add(tb_utilizador);
        tb_utilizador.setBounds(350, 230, 200, 50);

        pf_password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(pf_password);
        pf_password.setBounds(350, 290, 200, 50);

        jLabel1.setFont(new java.awt.Font("Alice in Wonderland", 0, 48)); // NOI18N
        jLabel1.setText("Utilizador:");
        add(jLabel1);
        jLabel1.setBounds(140, 230, 180, 50);

        jLabel2.setFont(new java.awt.Font("Alice in Wonderland", 0, 48)); // NOI18N
        jLabel2.setText("Palavra Pass:");
        add(jLabel2);
        jLabel2.setBounds(140, 300, 200, 40);

        jLabel4.setFont(new java.awt.Font("Alice in Wonderland", 0, 48)); // NOI18N
        jLabel4.setText("Criar Conta");
        add(jLabel4);
        jLabel4.setBounds(400, 160, 200, 40);

        bt_ret.setContentAreaFilled(false);
        bt_ret.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_ret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_retActionPerformed(evt);
            }
        });
        add(bt_ret);
        bt_ret.setBounds(100, 523, 60, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/login1.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(0, 0, 1000, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_retActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_retActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_retActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ok;
    private javax.swing.JButton bt_ret;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField tb_utilizador;
    // End of variables declaration//GEN-END:variables
}
